[CONTENT REVIEW] 21.4 - Adicionar requisito de Trigger ao projeto Vocabulary Booster
betrybe/sd-0x-mysql-vocabulary-booster-tests pull request #2
Opened 2020-11-26 22:08 UTC by orlando-messias

2020-11-27 11:36 UTC, roziscoding commented
Parece tudo OK pra mim.
@brunobatista25 pode dar um check aqui pra ver se os testes estão de boa?
Com o approve do Batista, por mim é :shipit:

2020-11-27 13:57 UTC, gomesanac requested changes

2020-11-27 13:57 UTC, gomesanac commented on tests/challengesResults/challengeResult120.js
> +const challengeResult20 = [
O nome do arquivo está como challengeResult**120**.js, acredito que deveria ser challengeResult**20**.js

2020-11-28 00:36 UTC, orlando-messias commented on tests/challengesResults/challengeResult120.js
> +const challengeResult20 = [
isso mesmo @gomesanac ótima observação. Jà corrigi

2020-11-30 13:45 UTC, nato-re approved these changes
LGTM

2020-11-30 13:54 UTC, gomesanac approved these changes

2020-11-30 19:14 UTC, roziscoding approved these changes

2021-01-06 17:45 UTC, merged

2021-01-06 17:52 UTC, brunobatista25 approved these changes